# Generated by OpenAI, 2025

import re

PATTERNS = [
    (r"(hi|hello|hey)", "Hi! How can I help?"),
    (r"(hours|open)", "We're open 9-5, Mon-Fri."),
    (r"(reset|password)", "Click 'Forgot password' on the sign-in page."),
]

def reply(user):
    text = user.lower()
    for pat, ans in PATTERNS:
        if re.search(pat, text):
            return ans
    return "I'm not sure yet—can you rephrase?"

if __name__ == "__main__":
    print("Bot: Hello! Ask me something. Type 'quit' to exit.")
    while True:
        msg = input("You: ")
        if msg.strip().lower() == "quit":
            break
        print("Bot:", reply(msg))
